name: Deploy to EC2

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/my-ec2-key.pem
        chmod 600 ~/.ssh/my-ec2-key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          echo "Pulling latest code"
          cd ~/myPortfolio
          git pull origin master

          echo "Stopping old container"
          docker stop myportfolio || true
          docker rm myportfolio || true

          echo "Building Docker image"
          docker build -t myportfolio .

          echo "Running new container"
          docker run -d -p 3001:3000 --name myportfolio myportfolio

          echo "!!!Deployment completed!!!"
        EOF
