name: Keep Render App Awake 2

on:
  schedule:
    - cron: '5-59/10 * * * *'
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render App
        run: |
          for i in {1..3}; do
            echo "[$(date '+%Y-%m-%d %H:%M:%S')] Wakeup Attempt $i"
            if curl --silent --show-error --fail https://myportfolio-y5qh.onrender.com; then
              echo "Success"
              break
            else
              echo "Failed, retrying after 10s..."
              sleep 10
            fi
          done
